### ISSUE TITLE
Issue with applet not opening windows

### ISSUE THREAD

**Issue by phocean** [dkopecek/usbguard#123]
There is an issue with the applet on Fedora 24 / Gnome 3.20.

Clicking on the tray icon opens the window only once.
Subsequent attempts to reopen it by clicking on this icon results in a quick open/close event (I can see it in the dash, but no window ever appears).

No console error is output.

PS: Wonderful tool, thanks a lot!

**Comment by dkopecek** [comment]
Hi and thanks for the report! As I'm not a Gnome desktop user, I haven't noticed this. Anyway, I'll try to reproduce this in a VM.

**Comment by phocean** [comment]
I am not using Wayland. Fedora 24 is still using Xorg by default.

**Comment by dkopecek** [comment]
Please try the latest Copr build. The issue should be addressed by commit c1f064a.

**Comment by phocean** [comment]
I just updated to usbguard-applet-qt.x86_64 0.6.1-0.1.1473773926.fc24 and it is actually worse than the previous version.

The previous version partially fixed the issue, in a way that simple click on the tray icon would not work, but double click did open the window correctly.

Now, following today's update, it does not work in both cases.

**Comment by dkopecek** [comment]
Ok, this one should definitely fix the issue. I've tested it in Gnome and it works for me. Copr builds should be available shortly.

**Comment by phocean** [comment]
The last update is perfect, no more issue at all.
Thank you very much !!

**Comment by dkopecek** [comment]
Great, thanks for testing!
